### ISSUE TITLE
sungwoncho:mailman

### ISSUE THREAD

**Issue by juliomac** [Meteor-Community-Packages/organization#65] opened 2022-08-03 14:27 UTC
## Links
* [Atmosphere](https://atmospherejs.com/sungwoncho/mailman)
* [Github repository](https://github.com/sungwoncho/meteor-mailman)

## Current status of the project
 * Abandoned

 ## Reasoning
It is simple to fix and helps a lot in development.

**Comment by StorytellerCZ** [comment] 2022-10-17 10:01
It has been a few months, but did not get a reply. So the next step would be to fork it. But before that we need volunteers who are going to take care of it, otherwise I don't want to increase our workload more than it already is.

**Comment by StorytellerCZ** [comment] 2022-11-17 13:42
Closing as duplicate of #62

**Closed by StorytellerCZ** 2022-11-17 13:42 UTC
